In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

def linear_regression(X1,y,learning_rate = 0.1, num_iters = 1000):
    X = np.c_[np.ones(len(X1)),X1]
    
    theta = np.zeros(X.shape[1]).reshape(-1,1)
    
    for _ in range(num_iters):
        
        predictions = (X).dot(theta).reshape(-1,1)
        
        errors=(predictions - y ).reshape(-1,1)
        
        theta -= learning_rate*(1/len(X1))*X.T.dot(errors)
    return theta

data=pd.read_csv("50_Startups.csv")
data.head()
X=(data.iloc[1:,:-2].values)
X1=X.astype(float)

scaler=StandardScaler()
y=(data.iloc[1:,-1].values).reshape(-1,1)

X1_Scaled=scaler.fit_transform(X1)
Y1_Scaled=scaler.fit_transform(y)
print(X1_Scaled)
print(Y1_Scaled)

theta= linear_regression(X1_Scaled,Y1_Scaled)

new_data=np.array([165349.2,136897.8,471784.1]).reshape(-1,1)

new_Scaled=scaler.fit_transform(new_data)
prediction=np.dot(np.append(1,new_Scaled),theta)
prediction=prediction.reshape(-1,1)
pre=scaler.inverse_transform(prediction)
print(prediction)
print(f"Predicted value: {pre}")

[[ 2.06444689e+00  1.08674530e+00  2.04710611e+00]
 [ 1.85614613e+00 -7.11896632e-01  1.73802284e+00]
 [ 1.64982664e+00 -8.43382418e-02  1.52544492e+00]
 [ 1.59829693e+00 -1.06114699e+00  1.37907465e+00]
 [ 1.36555729e+00 -7.59549576e-01  1.35065297e+00]
 [ 1.42785876e+00  9.37119267e-01 -6.70236359e-01]
 [ 1.32964071e+00  8.77364743e-01  1.01560916e+00]
 [ 1.10770332e+00  9.91548265e-01  9.10214603e-01]
 [ 1.17122873e+00 -4.42142808e-01  8.53220419e-01]
 [ 6.83888775e-01 -3.73575189e-01  2.01599152e-01]
 [ 6.55653643e-01 -1.04686585e+00  3.78499613e-01]
 [ 5.00768772e-01  2.25336793e-01  3.79315121e-01]
 [ 4.58195856e-01  5.18045196e-01  4.03598069e-01]
 [ 1.09406987e+00  1.27185968e+00  4.36668630e-01]
 [ 9.70774801e-01  5.69187019e-02  4.81902796e-01]
 [ 1.40171151e-01  2.04213242e-02  5.03988539e-01]
 [ 5.18818627e-01  8.61162942e-01  6.60646550e-01]
 [ 4.52662441e-01 -2.45327166e-01  7.66744716e-01]
 [ 3.31418719e-01  1.16324696e+00 -1.76786575e+00]
 [ 1.00148706e-01 -2.56373164e-